services:
  db_nestjs:
    image: postgres:16
    container_name: db_nestjs
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: store_nestjs
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: UTC
      PGTZ: UTC
    volumes:
      - pgdata_nestjs:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d store_nestjs"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis_nestjs:
    image: redis:7-alpine
    container_name: redis_nestjs
    restart: unless-stopped
    ports:
      - "6380:6379"
    environment:
      TZ: UTC
    volumes:
      - redisdata_nestjs:/data

  # backend_nestjs:
  #   build: .
  #   container_name: backend_nestjs
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   command: npm run start:dev
  #   depends_on:
  #     db_nestjs:
  #       condition: service_healthy
  #     redis_nestjs:
  #       condition: service_started
  #   environment:
  #     NODE_ENV: development
  #     PORT: 3000
  #     TZ: UTC
  #     DB_HOST: db_nestjs
  #     DB_PORT: 5432
  #     DB_USER: postgres
  #     DB_PASSWORD: ""
  #     DB_NAME: store_nestjs
  #     REDIS_URL: redis://redis_nestjs:6379
  #     REDIS_CACHE_TTL: 3600   
  #     JWT_ACCESS_SECRET: change_me_access_secret
  #     JWT_ACCESS_EXPIRATION: 900
  #     JWT_REFRESH_SECRET: change_me_refresh_secret
  #     JWT_REFRESH_EXPIRATION_DAYS: 7
  #     BCRYPT_SALT_ROUNDS: 10
  #   volumes:
  #     - ./src:/app/src

volumes:
  pgdata_nestjs:
  redisdata_nestjs:
